[global]
developmentMode = false

[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[client]
caching = true
displayEnabled = true

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"

[deprecation]
showfileUploaderEncoding = false
showPyplotGlobalUse = false

[cache]
ttl = 3600
maxEntrySize = 50 